#!/bin/sh
#
# jPaypal server startup script (FreeBSD rc.d)
#-------------------------------------------
#

# PROVIDE: jpaypal_server
# REQUIRE: LOGIN
# KEYWORD: shutdown

JPAYPAL_DIR=/usr/ws/jpaypal/jpaypal-server
USER=webreader	# a non root user of your unix server
JSVC=/opt/ws/commons-daemon/src/native/unix/jsvc	# see jsvc installation[1]
JAVA_HOME=/usr/local/openjdk6
#export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8118 -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8118 -DsocksProxyHost=localhost -DsocksProxyPort=9050
CLASS_PATH="${JPAYPAL_DIR}/target/classes:${JPAYPAL_DIR}/target/dependency/*"
CLASS=mars.jpaypal.server.Daemon
PID=/tmp/jpaypal-server-jsvc.pid
LOG_OUT=/tmp/jpaypal-server-jsvc.out
LOG_ERR=/tmp/jpaypal-server-jsvc.err


. /etc/rc.subr

name="jpaypal_server"
rcvar=jpaypal_server_enable

load_rc_config $name
: ${jpaypal_server_enable:=no}

start_postcmd="${name}_start"
stop_cmd="${name}_stop"

do_exec()
{
	$JSVC -home "$JAVA_HOME" -cp $CLASS_PATH -user $USER -outfile $LOG_OUT -errfile $LOG_ERR -pidfile $PID $1 $CLASS
}

inprogress_stop_dots()
{
while :;
	do
		sleep 1
		if [ -f "$PID" ]; then
			printf "."
		else
			break
		fi
done
}

jpaypal_server_start()
{
	do_exec;
}

jpaypal_server_stop()
{
	inprogress_stop_dots &
	do_exec "-stop";
}

run_rc_command "$1"


# [1] jsvc installation steps:
#  svn checkout http://svn.apache.org/repos/asf/commons/proper/daemon/trunk common-daemon
#  cd src/native/unix
#  sh support/buildconf.sh
#  ./configure --with-java=/usr/local/openjdk6
#  make
#  ./jsvc -help
#  export JAVA_HOME #If message says JAVA_HOME not found